[package]
name = "test-sentry-spans"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
sentry = "0.27.0"
sentry-tracing = "0.27.0"
